# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  repositoryName: "newdockerimage"

steps:
- task: Docker@2
  inputs:
    containerRegistry: docker-connection
    repository: $(repositoryName)
    command: 'buildandpush'
    Dockerfile: 'Dockerfile'